export const POINTS_LIST = {
  MAIN: [
    { xid: 'em_1_act_sum', name: 'Suma energii czynnej' },
    { xid: 'em_1_react_sum', name: 'Suma energii biernej', divider: true },
    { xid: 'em_1_l1', name: 'Prąd faza 1' },
    { xid: 'em_1_l2', name: 'Prąd faza 2' },
    { xid: 'em_1_l3', name: 'Prąd faza 3', divider: true },
    { xid: 'em_1_v12', name: 'Napięcie faza 1-2' },
    { xid: 'em_1_v23', name: 'Napięcie faza 2-3' },
    { xid: 'em_1_v31', name: 'Napięcie faza 3-1', divider: true },
    { xid: 'em_1_v1', name: 'Napięcie faza 1' },
    { xid: 'em_1_v2', name: 'Napięcie faza 2' },
    { xid: 'em_1_v3', name: 'Napięcie faza 3', divider: true },
    { xid: 'em_1_pow_act_1', name: 'Moc czynna faza 1' },
    { xid: 'em_1_pow_act_2', name: 'Moc czynna faza 2' },
    { xid: 'em_1_pow_act_3', name: 'Moc czynna faza 3', divider: true },
    { xid: 'em_1_pow_react_1', name: 'Moc bierna faza 1' },
    { xid: 'em_1_pow_react_2', name: 'Moc bierna faza 2' },
    { xid: 'em_1_pow_react_3', name: 'Moc bierna faza 3', divider: true },
    { xid: 'em_1_pow_app_1', name: 'Moc pozorna faza 1' },
    { xid: 'em_1_pow_app_2', name: 'Moc pozorna faza 2' },
    { xid: 'em_1_pow_app_3', name: 'Moc pozorna faza 3', divider: true },
    { xid: 'em_1_factor_1', name: 'Współczynnik mocy faza 1' },
    { xid: 'em_1_factor_2', name: 'Współczynnik mocy faza 2' },
    { xid: 'em_1_factor_3', name: 'Współczynnik mocy faza 3' },
    { xid: 'em_1_freq', name: 'Częstotliwość', divider: true },
    { xid: 'em_1_v_avg', name: 'Średnie napięcie fazowe' },
    { xid: 'em_1_v123_avg', name: 'Średnie napięcie międzyfazowe', divider: true },
    { xid: 'em_1_pow_act_avg', name: 'Średnia moc czynna' },
    { xid: 'em_1_pow_react_avg', name: 'Średnia moc bierna' },
    { xid: 'em_1_pow_app_avg', name: 'Średnia moc pozorna' },
    { xid: 'em_1_factor_avg', name: 'Średni współczynnik mocy', divider: true },
    { xid: 'em_1_com', name: 'Połączenie' },
  ],
  AIRCONDITIONING: [
    { xid: 'em_2_act_sum', name: 'Suma energii czynnej' },
    { xid: 'em_2_react_sum', name: 'Suma energii biernej', divider: true },
    { xid: 'em_2_l1', name: 'Prąd faza 1' },
    { xid: 'em_2_l2', name: 'Prąd faza 2' },
    { xid: 'em_2_l3', name: 'Prąd faza 3', divider: true },
    { xid: 'em_2_v12', name: 'Napięcie faza 1-2' },
    { xid: 'em_2_v23', name: 'Napięcie faza 2-3' },
    { xid: 'em_2_v31', name: 'Napięcie faza 3-1', divider: true },
    { xid: 'em_2_v1', name: 'Napięcie faza 1' },
    { xid: 'em_2_v2', name: 'Napięcie faza 2' },
    { xid: 'em_2_v3', name: 'Napięcie faza 3', divider: true },
    { xid: 'em_2_pow_act_1', name: 'Moc czynna faza 1' },
    { xid: 'em_2_pow_act_2', name: 'Moc czynna faza 2' },
    { xid: 'em_2_pow_act_3', name: 'Moc czynna faza 3', divider: true },
    { xid: 'em_2_pow_react_1', name: 'Moc bierna faza 1' },
    { xid: 'em_2_pow_react_2', name: 'Moc bierna faza 2' },
    { xid: 'em_2_pow_react_3', name: 'Moc bierna faza 3', divider: true },
    { xid: 'em_2_pow_app_1', name: 'Moc pozorna faza 1' },
    { xid: 'em_2_pow_app_2', name: 'Moc pozorna faza 2' },
    { xid: 'em_2_pow_app_3', name: 'Moc pozorna faza 3', divider: true },
    { xid: 'em_2_factor_1', name: 'Współczynnik mocy faza 1' },
    { xid: 'em_2_factor_2', name: 'Współczynnik mocy faza 2' },
    { xid: 'em_2_factor_3', name: 'Współczynnik mocy faza 3' },
    { xid: 'em_2_freq', name: 'Częstotliwość', divider: true },
    { xid: 'em_2_v_avg', name: 'Średnie napięcie fazowe' },
    { xid: 'em_2_v123_avg', name: 'Średnie napięcie międzyfazowe', divider: true },
    { xid: 'em_2_pow_act_avg', name: 'Średnia moc czynna' },
    { xid: 'em_2_pow_react_avg', name: 'Średnia moc bierna' },
    { xid: 'em_2_pow_app_avg', name: 'Średnia moc pozorna' },
    { xid: 'em_2_factor_avg', name: 'Średni współczynnik mocy', divider: true },
    { xid: 'em_2_com', name: 'Połączenie' },
  ]
}