// @TODO
const definitions = [
    ["Centrala - nagrzewnica elektryczna", "hepwr"],
    ["Centrala - nagrzewnica wodna", "y1"],
    ["Centrala - nastawa temperatury", "tset"],
    ["Centrala - pompa nagrzewnicy", "m1"],
    ["Centrala - przepustnice", "throt"],
    ["Centrala - stan układu", "unitstate"],
    ["Centrala - temperatura nawiewu", "b1"],
    ["Centrala - temperatura wiodąca", "tmain"],
    ["Centrala - temperatura wywiewu", "b2"],
    ["Centrala - temperatura za odzyskiem", "b4"],
    ["Centrala - temperatura zadana", "tsetactual"],
    ["Centrala - temperatura zewnętrzna", "b3"],
    ["Centrala - wentylator nawiewu", "pwrsup"],
    ["Centrala - wentylator wywiewu", "pwrexh"],
    ["Centrala - wentylatory", "vent"],
    ["Centrala - wysterowanie odzysku", "yrec"],
    ["Centrala - wysterowanie odzysku", "recstate"],
    ["Klimakonwektor - kasy - alarm", "fc_c_alarm"],
    ["Klimakonwektor - kasy - połączenie", "fc_c_com"],
    ["Klimakonwektor - kasy - stan", "fc_c_onoff"],
    ["Klimakonwektor - kasy - temperatura wiodąca", "fc_c_tmain"],
    ["Klimakonwektor - kasy - temperatura zadana", "fc_c_tset"],
    ["Klimakonwektor - kasy - tryb", "fc_c_mode"],
    ["Klimakonwektor - kasy - tryb temperatury", "fc_c_modetemp"],
    ["Klimakonwektor - kasy - wentylator", "fc_c_vent"],
    ["Klimakonwektor - kasy - zawór nagrzewnicy", "fc_c_y1"],
    ["Klimakonwektor - strefa 2 - alarm", "fc_s2_alarm"],
    ["Klimakonwektor - strefa 2 - połączenie", "fc_s2_com"],
    ["Klimakonwektor - strefa 2 - stan", "fc_s2_onoff"],
    ["Klimakonwektor - strefa 2 - temperatura wiodąca", "fc_s2_tmain"],
    ["Klimakonwektor - strefa 2 - temperatura zadana", "fc_s2_tset"],
    ["Klimakonwektor - strefa 2 - tryb", "fc_s2_mode"],
    ["Klimakonwektor - strefa 2 - tryb temperatury", "fc_s2_modetemp"],
    ["Klimakonwektor - strefa 2 - wentylator", "fc_s2_vent"],
    ["Klimakonwektor - strefa 2 - zawór nagrzewnicy", "fc_s2_y1"],
    ["Klimakonwektor - strefa 3 - alarm", "fc_s3_alarm"],
    ["Klimakonwektor - strefa 3 - połączenie", "fc_s3_com"],
    ["Klimakonwektor - strefa 3 - stan", "fc_s3_onoff"],
    ["Klimakonwektor - strefa 3 - temperatura wiodąca", "fc_s3_tmain"],
    ["Klimakonwektor - strefa 3 - temperatura zadana", "fc_s3_tset"],
    ["Klimakonwektor - strefa 3 - tryb", "fc_s3_mode"],
    ["Klimakonwektor - strefa 3 - tryb temperatury", "fc_s3_modetemp"],
    ["Klimakonwektor - strefa 3 - wentylator", "fc_s3_vent"],
    ["Klimakonwektor - strefa 3 - zawór nagrzewnicy", "fc_s3_y1"],
    ["Klimakonwektor - strefa 4 - alarm", "fc_s4_alarm"],
    ["Klimakonwektor - strefa 4 - połączenie", "fc_s4_com"],
    ["Klimakonwektor - strefa 4 - stan", "fc_s4_onoff"],
    ["Klimakonwektor - strefa 4 - temperatura wiodąca", "fc_s4_tmain"],
    ["Klimakonwektor - strefa 4 - temperatura zadana", "fc_s4_tset"],
    ["Klimakonwektor - strefa 4 - tryb", "fc_s4_mode"],
    ["Klimakonwektor - strefa 4 - tryb temperatury", "fc_s4_modetemp"],
    ["Klimakonwektor - strefa 4 - wentylator", "fc_s4_vent"],
    ["Klimakonwektor - strefa 4 - zawór nagrzewnicy", "fc_s4_y1"],
    ["Klimatyzator - kasy - alarm", "ac_c_alarm"],
    ["Klimatyzator - kasy - bieg", "ac_c_speed"],
    ["Klimatyzator - kasy - łopatki", "ac_c_vanes"],
    ["Klimatyzator - kasy - połączenie", "ac_c_com"],
    ["Klimatyzator - kasy - stan", "ac_c_onoff"],
    ["Klimatyzator - kasy - temperatura wiodąca", "ac_c_treg"],
    ["Klimatyzator - kasy - tryb", "ac_c_mode"],
    ["Klimatyzator - strefa 2 - alarm", "ac_s2_alarm"],
    ["Klimatyzator - strefa 2 - bieg", "ac_s2_speed"],
    ["Klimatyzator - strefa 2 - łopatki", "ac_s2_vanes"],
    ["Klimatyzator - strefa 2 - połączenie", "ac_s2_com"],
    ["Klimatyzator - strefa 2 - stan", "ac_s2_onoff"],
    ["Klimatyzator - strefa 2 - temperatura wiodąca", "ac_s2_treg"],
    ["Klimatyzator - strefa 2 - tryb", "ac_s2_mode"],
    ["Klimatyzator - strefa 3 - alarm", "ac_s3_alarm"],
    ["Klimatyzator - strefa 3 - bieg", "ac_s3_speed"],
    ["Klimatyzator - strefa 3 - łopatki", "ac_s3_vanes"],
    ["Klimatyzator - strefa 3 - połączenie", "ac_s3_com"],
    ["Klimatyzator - strefa 3 - stan", "ac_s3_onoff"],
    ["Klimatyzator - strefa 3 - temperatura wiodąca", "ac_s3_treg"],
    ["Klimatyzator - strefa 3 - tryb", "ac_s3_mode"],
    ["Klimatyzator - strefa 4 - alarm", "ac_s4_alarm"],
    ["Klimatyzator - strefa 4 - bieg", "ac_s4_speed"],
    ["Klimatyzator - strefa 4 - łopatki", "ac_s4_vanes"],
    ["Klimatyzator - strefa 4 - połączenie", "ac_s4_com"],
    ["Klimatyzator - strefa 4 - stan", "ac_s4_onoff"],
    ["Klimatyzator - strefa 4 - temperatura wiodąca", "ac_s4_treg"],
    ["Klimatyzator - strefa 4 - tryb", "ac_s4_mode"],
    ["Klimatyzator - zaplecze - alarm", "ac_z_alarm"],
    ["Klimatyzator - zaplecze - bieg", "ac_z_speed"],
    ["Klimatyzator - zaplecze - łopatki", "ac_z_vanes"],
    ["Klimatyzator - zaplecze - połączenie", "ac_z_com"],
    ["Klimatyzator - zaplecze - stan", "ac_z_onoff"],
    ["Klimatyzator - zaplecze - temperatura wiodąca", "ac_z_treg"],
    ["Klimatyzator - zaplecze - tryb", "ac_z_mode"],
    ["Kurtyna - alarm", "cur_alarm"],
    ["Kurtyna - nagrzewnica", "cur_heat"],
    ["Kurtyna - połączenie", "cur_com"],
    ["Kurtyna - stan", "cur_onoff"],
    ["Kurtyna - temperatura zewnętrzna", "cur_tout"],
    ["Kurtyna - tryb", "cur_mode"],
    ["Kurtyna - wysterowanie wentylatora", "cur_vent_pwr"],
    ["Kurtyna 2 - alarm", "cur2_alarm"],
    ["Kurtyna 2 - nagrzewnica", "cur2_heat"],
    ["Kurtyna 2 - połączenie", "cur2_com"],
    ["Kurtyna 2 - stan", "cur2_onoff"],
    ["Kurtyna 2 - temperatura zewnętrzna", "cur2_tout"],
    ["Kurtyna 2 - tryb", "cur2_mode"],
    ["Kurtyna 2 - wysterowanie wentylatora", "cur2_vent_pwr"],
    ["Licznik energii - moc czynna faza 1", "m_pow1"],
    ["Licznik energii - moc czynna faza 2", "m_pow2"],
    ["Licznik energii - moc czynna faza 3", "m_pow3"],
    ["Licznik energii - połączenie", "m_com"],
    ["Licznik energii - prąd faza 1", "m_l1"],
    ["Licznik energii - prąd faza 2", "m_l2"],
    ["Licznik energii - prąd faza 3", "m_l3"],
    ["Licznik energii - średnia moc czynna", "m_pow_avg_act"],
    ["Licznik energii - zużycie energii biernej", "m_sum_react"],
    ["Licznik energii - zużycie energii czynnej", "consumption"],
    ["Licznik energii - zużycie ostatni miesiąc", "energymonth"],
    ["Licznik energii - zużycie ostatni tydzień", "energy7"],
    ["Licznik energii - zużycie ostatnia doba", "energy24"],
    ["Nastawa temperatury strefa kas", "tset_klim"],
    ["Nastawa temperatury strefa ogólna", "tseto"],
    ["Pompa ciepła - kasy - alarm", "pc_c_alarm"],
    ["Pompa ciepła - kasy - połączenie", "pc_c_com"],
    ["Pompa ciepła - kasy - sprężarka", "pc_c_spr"],
    ["Pompa ciepła - kasy - stan", "pc_c_onoffr"],
    ["Pompa ciepła - kasy - temperatura wiodąca", "pc_c_tmain"],
    ["Pompa ciepła - kasy - temperatura zadana", "pc_c_tset"],
    ["Pompa ciepła - kasy - tryb", "pc_c_mode"],
    ["Pompa ciepła - kasy - wentylator", "pc_c_vent"],
    ["Pompa ciepła - kasy - zawór chłodzenie", "pc_c_cool"],
    ["Pompa ciepła - kasy - zawór grzanie", "pc_c_heat"],
    ["Pompa ciepła - strefa 2 - alarm", "pc_s2_alarm"],
    ["Pompa ciepła - strefa 2 - połączenie", "pc_s2_com"],
    ["Pompa ciepła - strefa 2 - sprężarka", "pc_s2_spr"],
    ["Pompa ciepła - strefa 2 - stan", "pc_s2_onoffr"],
    ["Pompa ciepła - strefa 2 - temperatura wiodąca", "pc_s2_tmain"],
    ["Pompa ciepła - strefa 2 - temperatura zadana", "pc_s2_tset"],
    ["Pompa ciepła - strefa 2 - tryb", "pc_s2_mode"],
    ["Pompa ciepła - strefa 2 - wentylator", "pc_s2_vent"],
    ["Pompa ciepła - strefa 2 - zawór chłodzenie", "pc_s2_cool"],
    ["Pompa ciepła - strefa 2 - zawór grzanie", "pc_s2_heat"],
    ["Pompa ciepła - strefa 3 - alarm", "pc_s3_alarm"],
    ["Pompa ciepła - strefa 3 - połączenie", "pc_s3_com"],
    ["Pompa ciepła - strefa 3 - sprężarka", "pc_s3_spr"],
    ["Pompa ciepła - strefa 3 - stan", "pc_s3_onoffr"],
    ["Pompa ciepła - strefa 3 - temperatura wiodąca", "pc_s3_tmain"],
    ["Pompa ciepła - strefa 3 - temperatura zadana", "pc_s3_tset"],
    ["Pompa ciepła - strefa 3 - tryb", "pc_s3_mode"],
    ["Pompa ciepła - strefa 3 - wentylator", "pc_s3_vent"],
    ["Pompa ciepła - strefa 3 - zawór chłodzenie", "pc_s3_cool"],
    ["Pompa ciepła - strefa 3 - zawór grzanie", "pc_s3_heat"],
    ["Stan układu", "mode"],
    ["Temperatura pomieszczenia rozliczeń", "b5"],
    ["Temperatura średnia strefa kas", "tmain_kasy"],
    ["Temperatura średnia wewnątrz", "tavr"],
    ["Tryb pracy", "workmode"],
];


const autoFillRegister = (
    pointRef: PointRegisterReference
): PointRegisterReference => {
            const foundDefinition = definitions.find(def => def[1].toLowerCase() === (pointRef.registerName || pointRef.name).toLowerCase())

            return {
                ...pointRef,
                name: foundDefinition ? foundDefinition[0] : pointRef.name
            };
};

export default autoFillRegister;
